

FROM        --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL       author="NexoHost Corporation" maintainer="support@nexohost.es"

LABEL       org.opencontainers.image.source="https://github.com/NexoHost/yolks"
LABEL       org.opencontainers.image.licenses=MIT

RUN         apk add --update --no-cache ca-certificates curl git jq wget
